package daemon

import (
	"context"
	"os"
	"path/filepath"
	"sync/atomic"
	"testing"
	"time"

	"github.com/fsnotify/fsnotify"
)

// newTestRepoWatcher wires a repoWatcher around a real fsnotify watch on repo
// with the reindex body replaced by doReindex. It drives the same run loop as
// production; only the build+swap work is faked.
func newTestRepoWatcher(t *testing.T, repo string, doReindex func(ctx context.Context)) *repoWatcher {
	t.Helper()
	fsw, err := fsnotify.NewWatcher()
	if err != nil {
		t.Fatal(err)
	}
	if err := fsw.Add(repo); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	rw := &repoWatcher{
		repoPath:  repo,
		fsw:       fsw,
		cancel:    cancel,
		done:      make(chan struct{}),
		doReindex: doReindex,
	}
	go rw.run(ctx)
	t.Cleanup(rw.Close)
	return rw
}

// TestRelevantEventIgnoresChmodOnly is the regression test for the reindex
// loop that kernel-panicked the machine: on the kqueue backends a bare
// NOTE_ATTRIB (atime update from git re-hashing a dirty file via mmap) arrives
// as a Chmod-only event. An attribute change never changes file content, so it
// must not schedule a reindex.
func TestRelevantEventIgnoresChmodOnly(t *testing.T) {
	repo := t.TempDir()
	rw := &repoWatcher{repoPath: repo}

	chmodOnly := fsnotify.Event{Name: filepath.Join(repo, "main.go"), Op: fsnotify.Chmod}
	if rw.relevantEvent(chmodOnly) {
		t.Fatal("Chmod-only event on a source file must be ignored")
	}

	// A write that arrives coalesced with an attribute change is still a write.
	writeChmod := fsnotify.Event{Name: filepath.Join(repo, "main.go"), Op: fsnotify.Write | fsnotify.Chmod}
	if !rw.relevantEvent(writeChmod) {
		t.Fatal("Write|Chmod event on a source file must stay relevant")
	}
}

// TestReindexIgnoresOwnEvents: events generated by the reindex itself — a
// temp file with a source extension created and deleted while the build runs —
// must not schedule a follow-up reindex. This was the loop mechanism: each
// rebuild's own filesystem side effects re-armed the debounce forever.
func TestReindexIgnoresOwnEvents(t *testing.T) {
	repo := t.TempDir()
	var runs atomic.Int32
	rw := newTestRepoWatcher(t, repo, func(ctx context.Context) {
		runs.Add(1)
		// Simulate the indexer briefly creating a source-extension temp file
		// inside the watched repo, then removing it.
		tmp := filepath.Join(repo, "indexer_tmp.go")
		if err := os.WriteFile(tmp, []byte("package x\n"), 0o644); err != nil {
			t.Error(err)
		}
		time.Sleep(500 * time.Millisecond) // let the events arrive mid-flight
		os.Remove(tmp)
		time.Sleep(200 * time.Millisecond)
	})
	_ = rw

	// One real edit kicks things off.
	if err := os.WriteFile(filepath.Join(repo, "real.go"), []byte("package x\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Wait past debounce + reindex + cooldown + any (buggy) follow-up cycles.
	deadline := time.After(6 * time.Second)
	<-deadline
	if got := runs.Load(); got != 1 {
		t.Fatalf("want exactly 1 reindex for one user edit, got %d", got)
	}
}

// TestReindexCatchesEditDuringBuild: a real user edit made while a reindex is
// in flight must not be lost — it gets exactly one catch-up reindex once the
// in-flight build finishes, and the catch-up does not itself loop.
func TestReindexCatchesEditDuringBuild(t *testing.T) {
	repo := t.TempDir()
	var runs atomic.Int32
	editDone := make(chan struct{})
	rw := newTestRepoWatcher(t, repo, func(ctx context.Context) {
		if runs.Add(1) == 1 {
			// First build: a user edit lands mid-flight and persists.
			if err := os.WriteFile(filepath.Join(repo, "edited.go"), []byte("package x\n"), 0o644); err != nil {
				t.Error(err)
			}
			close(editDone)
			time.Sleep(500 * time.Millisecond)
		}
	})
	_ = rw

	if err := os.WriteFile(filepath.Join(repo, "seed.go"), []byte("package x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	<-editDone

	// Allow first build to finish, cooldown to pass, catch-up to run, and any
	// (buggy) extra cycles to show themselves.
	time.Sleep(6 * time.Second)
	if got := runs.Load(); got != 2 {
		t.Fatalf("want exactly 2 reindexes (initial + one catch-up for the mid-build edit), got %d", got)
	}
}
